### ISSUE TITLE
Change the static download file path to dynamic

### ISSUE THREAD

**Issue by amrs-tech** [amrs-tech/Desktop-Wallpaper-Changer#2]
The download path in the program is static to my local machine. Try to make it dynamic such that the program itself searches the directory where the file is downloaded. :)

**Comment by abotiamnot** [comment]
Sounds good, will fix this!

**Comment by dnafication** [comment]
Yes, we can also add support to different operating systems. I think it currently only works on Windows. What do you guys think?

**Comment by abotiamnot** [comment]
That is a required functionality, could do that as well!

**Comment by amrs-tech** [comment]
> Yes, we can also add support to different operating systems. I think it currently only works on Windows. What do you guys think?

@dnafication Yeah, thanks. That would be good. :)

**Comment by amrs-tech** [comment]
Thanks for helping out :)
